#! /bin/bash

function handler()
{
    echo "                                 "
    echo "          Cleaning up!           "
    echo "================================="
    kill -s SIGINT $PID
    ps ax | grep -E "uvicorn|from multiprocessing" | grep -v grep | awk '{print "kill -9 " $1}' | sh
    echo "Thank you for running Deez Notes!"
    exit
}
trap handler exit
echo "================================="
echo "      Running Deez Notes!        "

if [ ! -d "log/" ]
then
    mkdir log
fi

output="$(lsof -i tcp:3000 | grep LISTEN)"
if [[ ${#output} -ge 2 ]] 
then
    echo "Port 3000 (where the frontend would like to run) already taken. Please free the port then run again."
    echo "run the command: lsof -i tcp:3000 to see which process is using that port"
    exit
fi

output="$(lsof -i tcp:8000 | grep LISTEN)"
if [[ ${#output} -ge 2 ]] 
then
    echo "Port 8000 (where the backend would like to run) already taken. Please free the port then run again."
    echo "run the command: lsof -i tcp:8000 to see which process is using that port"
    exit
fi


cd backend
uvicorn backend:app --reload &> ../log/backend_out.txt &
PID=$!
cd ../frontend
npm start &> ../log/frontend_out.txt
# PID2=$!

trap handler SIGINT SIGKILL

